analytics: {}
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0
  lightness: 0.833757
  rhythmicContrast: 0.258125
  saturation: 0
cta: {}
layout_spectrum: 0.1558385258815903
name: FSK
opengraph: {}
purpose: {}
typography_spectrum: 0.2005356769214235
